spring.application.name=reservation-service
server.port=8083
spring.datasource.url=jdbc:h2:mem:reservationdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
clients.room.url=http://localhost:8081
clients.member.url=http://localhost:8082
